background            #141515
foreground            #cbc2be

# black
color0  #141515
color8  #4b4e55

# red
color1  #565d60
color9  #978e8c

# green
color2  #9fa5a9
color10 #343d41

# yellow
color3  #d9dbdc
color11 #c9c2b4

# blue
color4  #798186
color12 #5d6367

# magenta
color5  #aeaeae
color13 #9a9a9a

#cyan
color6  #707070
color14 #707070

#white
color7  #cbc2be
color15 #a5aeb4


